language : node_js
node_js :  
 - stable
script:  
 - npm run ci
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: 1c3ffe8ba1014d53a1b94e8628a8b58bdc0aa28b
    on:
      tags: true
  - provider: releases
    api_key: 1c3ffe8ba1014d53a1b94e8628a8b58bdc0aa28b
    file_glob: true
    file: "{YOURLIB}-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "zishgarces@gmail.com"
    api_key: 26eaccb0-e48e-4164-a818-84494d987a4a
    on:
      tags: true