name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish-npm:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/ 
      - run: npm ci
      # - name: publish on npm
        # run: npm publish
        # env:
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - name: set registry
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
      - name: publish on gpr
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
